version: '3.3'

services:
  db-plemousse:
    image: dbplemousse
    build:
      context: . # Use an image built from the specified dockerfile in the `pampleback_app` directory.
      dockerfile: .\docker\db\Dockerfile
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${MYSQLDB_DATABASE}
      # So you don't have to use root, but you can if you like
      MYSQL_USER: ${MYSQLDB_USER}
      # You can use whatever password you like
      MYSQL_PASSWORD: ${MYSQLDB_PASSWORD}
      # Password for root access
      MYSQL_ROOT_PASSWORD: ${MYSQLDB_ROOT_PASSWORD}
      
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - ${MYSQLDB_LOCAL_PORT}:${MYSQLDB_DOCKER_PORT}
    expose:
      # Opens port 3306 on the container
      - ${MYSQLDB_DOCKER_PORT}
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
      - ./src/main/resources/sql:/docker-entrypoint-initdb.d
    networks:
      my-networks:

  # App backend service
  pampleback_app:
    image: pampleback
    # Configuration for building the docker image for the backend service
    build:
      context: . # Use an image built from the specified dockerfile in the `pampleback_app` directory.
      dockerfile: .\docker\back\Dockerfile
    env_file:
      - .env
    ports:
      - ${SPRING_LOCAL_PORT}:${SPRING_LOCAL_PORT} # Forward the exposed port 8080 on the container to port 8080 on the host machine
    expose:
      - ${SPRING_LOCAL_PORT}
    restart: unless-stopped
    depends_on: 
      - db-plemousse # This service depends on mysql. Start that first.
    links:
      - db-plemousse
    environment: # Pass environment variables to the service
      SPRING_DATASOURCE_URL: jdbc:mysql://db-plemousse:${MYSQLDB_DOCKER_PORT}/${MYSQLDB_DATABASE}
      SPRING_DATASOURCE_USERNAME: ${MYSQLDB_ROOT_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQLDB_ROOT_PASSWORD}
    networks:
      my-networks:

volumes:
  my-db:

networks:
  my-networks: