version: '3.3'

services:
  db-plemousse:
    image: dbplemousse
    build:
      context: . # Use an image built from the specified dockerfile in the `pampleback_app` directory.
      dockerfile: .\docker\db\Dockerfile
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${MYSQLDB_DATABASE}
      # So you don't have to use root, but you can if you like
      MYSQL_USER: ${MYSQLDB_USER}
      # You can use whatever password you like
      MYSQL_PASSWORD: ${MYSQLDB_PASSWORD}
      # Password for root access
      MYSQL_ROOT_PASSWORD: ${MYSQLDB_ROOT_PASSWORD}
      
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - ${MYSQLDB_LOCAL_PORT}:${MYSQLDB_DOCKER_PORT}
    expose:
      # Opens port 3306 on the container
      - ${MYSQLDB_DOCKER_PORT}
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
      - ./src/main/resources/sql:/docker-entrypoint-initdb.d
    networks:
      my-networks:

volumes:
  my-db:

networks:
  my-networks: